#!/bin/sh

set -eux

if ! type git > /dev/null 2>&1; then
  echo "ERROR: git not found (brew install git)"
  exit 1
fi

REPO_NAME=${1:-template-dockerfile}
git clone --depth 1 https://github.com/tmknom/template-dockerfile.git "${REPO_NAME}"

cd "${REPO_NAME}"
rm -rf install .git
sed -i "" -e "s/template-dockerfile/${REPO_NAME}/g" README.md
sed -i "" -e "s/template-dockerfile/${REPO_NAME}/g" Makefile

git init
git add .
git commit -m "Initial commit" -m "Based on https://github.com/tmknom/template-dockerfile"

set +x
echo "\n  Install success!"
echo "\nNext step: cd ${REPO_NAME}"
