#!/bin/bash
#
# https://docs.docker.com/docker-cloud/builds/advanced/
docker build \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VERSION=${CACHE_TAG} \
  --build-arg PROJECT_NAME=${DOCKER_REPO} \
  -t ${IMAGE_NAME} .
