name: Shell Script
on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        pattern:
          - install
          - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: ShellCheck
        uses: reviewdog/action-shellcheck@v1.1.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: ${{ matrix.pattern }}
